#!/bin/bash

function main() {

    local version=$(cat $(dirname $0)/pom.xml | grep "module.release.version>")
    version=${version#*version>}
    version=${version%%?/*}

    local release_file=$(dirname $0)/release/target/events-${version}.zip

    [ -z ${RUNTIME_DIR} ] && { echo "RUNTIME_DIR not defined" 1>&2; exit 1; }

    [ -d ${RUNTIME_DIR}/events-${version} ] &&  { echo "events-${version} already installed" 1>&2; exit 1; }

    [ ! -f ${release_file} ] && { echo "release file ${release_file} not found" 1>&2; exit 1; }

    cp ${release_file} ${RUNTIME_DIR}
    (cd ${RUNTIME_DIR}; unzip events-${version}.zip)
    ${RUNTIME_DIR}/events-${version}/bin/.install
    rm  ${RUNTIME_DIR}/events-${version}.zip

}

main;



