/*
 * Copyright (c) 2016 Nova Ordis LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.novaordis.events.extensions.bscenarios;

import io.novaordis.events.core.event.FaultType;

/**
 * @author Ovidiu Feodorov <ovidiu@novaordis.com>
 * @since 4/23/16
 */
public enum BusinessScenarioFaultType implements FaultType {

    NO_JSESSIONID_COOKIE,            // the request does not have a JSESSIONID cookie, which means it was sent before
                                     // authentication and session establishment, or after the session was closed.
                                     // These requests are reported in summary statistics and usually ignored.

    NO_OPEN_BUSINESS_SCENARIO,       // these faults are generated by the request arriving "between" scenarios.
                                     // This is a normal condition and they should be usually ignored.

    NO_REQUEST_DURATION_INFO,        // no request duration information was found in the input data stream. This fault
                                     // indicates a potentially serious condition, as it won't be possible to calculate
                                     // request and business scenario durations.

    DUPLICATE_REQUEST_SEQUENCE_ID,   // a business scenario receives duplicate request sequence IDs

    SUDDEN_ITERATION_IDS,            // the business scenario is suddenly starting to see iteration IDs after
                                     // it started without one

    MULTIPLE_ITERATION_IDS,          // a business scenario sees more than one iteration ID during its life

    MISSING_ITERATION_ID,            // the business scenario started with a non-null iteration ID, but
                                     // it does not see an iteration ID anymore

}
